services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bookstore-network

  eureka-service:
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    container_name: eureka-service
    restart: on-failure
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bookstore-network

  postgres-auth:
    image: postgres:17
    platform: linux/arm64
    container_name: postgres-auth
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - bookstore-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: on-failure
    depends_on:
      postgres-auth:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
    env_file:
      - ./auth-service/.env.auth
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/
    ports:
      - "8081:8081"
    networks:
      - bookstore-network

  postgres-catalog:
    image: postgres:17
    platform: linux/arm64
    container_name: postgres-catalog
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog_db
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_catalog_data:/var/lib/postgresql/data
    networks:
      - bookstore-network

  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    container_name: catalog-service
    restart: on-failure
    depends_on:
      postgres-catalog:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
    env_file:
      - ./catalog-service/.env.catalog
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/
    ports:
      - "8082:8082"
    networks:
      - bookstore-network

  postgres-order:
    image: postgres:17
    platform: linux/arm64
    container_name: postgres-order
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
    networks:
      - bookstore-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    restart: on-failure
    depends_on:
      postgres-order:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
    env_file:
      - ./order-service/.env.order
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/
    ports:
      - "8083:8083"
    networks:
      - bookstore-network

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    restart: on-failure
    depends_on:
      - eureka-service
      - auth-service
      - catalog-service
      - order-service
    ports:
      - "8080:8080"
    networks:
      - bookstore-network
    env_file:
      - ./gateway-service/.env.gateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/

networks:
  bookstore-network:

volumes:
  postgres_auth_data:
  postgres_catalog_data:
  postgres_order_data: